### ISSUE TITLE
error calculating steam  T(P,H) between 4 and 4.5257578905948002 MPa 

### ISSUE THREAD

**Issue by marting-m** [CoolProp/IF97#35]
Hi, I think I found an issue using IF97.h file in a project. Perhaps a compiler option can solve it but I found a possible solution

Obtaining T(P,H) gives wrong results for steam in the range (4 - 4.526 Mpa), example:

For P=4.15 Mpa and T= 700K
 H(P,T) = 3.27503e6 J/kg

T(P,H)= **721.13K**

The problem comes from sqrt (<0) in 
Line  3771
`            const double ETA = region2b2c_n[3] + sqrt((PI - region2b2c_n[4])/region2b2c_n[2]);
`
Proposed solution: 

Lines 4025... 
```
//						   else if (X >= Backwards::H2b2c_p(p))
//							   return B2bH.T_pX(p, X);
//						   else
//							   return B2cH.T_pX(p, X);
// MMG 2022.04.19  
// Backwards::H2b2c_p(p) returns nan betweeen 4 and 4,526 MPa choosing wrong subregion
// changing the comparison solves the issue 
 						   else if (X < Backwards::H2b2c_p(p))
 							   return B2cH.T_pX(p, X);
 						   else
							   return B2bH.T_pX(p, X);

```

**Comment by henningjp** [comment]
@marting-m  Well, that works for your specific case, but I think I found the root cause.

The validation and region boundary P-H diagram is shown below.  The boundary between region 2a and 2b is a horizontal line at 4 MPa.  This is the lower limit you determined for the problem area.  I mistakenly assumed that the boundary curve between region 2b and 2c reached all the way down to 4 MPa on the saturation curve.  It does not.  It stops at P = 6.54670 MPa [per IAPWS R7-97(2012)] on the saturation curve.  The failing equation at Line 3771 is trying to evaluate that 2b/2c boundary beyond the end of the curve and into the vapor dome.  This gap between 4 MPa and 6.54670 MPa must be accounted for and your pressures fall within this range.  

![P-H Regions Gap](https://user-images.githubusercontent.com/17114032/164163538-ce653d63-e75d-436e-8294-a06afe12d53a.png)

Interestingly, none of the IAPWS validation points in sub-region 2b are close enough to the saturation curve to cause this to fail.  It's also interesting that the sqrt(<0) doesn't just crash instead of returning the wrong region.

I'll shore this up, unless you want to put a PR in.  At line 4025 anything between 4 MPa and 6.54670 MPa should default to sub-region 2b without checking the region 2b/2c curve.  Same applies to the Entropy logic starting on line 4030.  If not, I'll take care of it.

**Comment by marting-m** [comment]
Hi @henningjp,
I was also surprised that X<(NaN) was false, and I decided to take that shortcut. 
Probably this is compiler dependent so it's better to assure checking the pressure.
Thanks for your quick answer and for pointing about the entropy case,

**Comment by henningjp** [comment]
@marting-m - That definitely fixed it.  The T(P,S) function is unaffected because the boundary is a straight line of constant S; no square root of negative results.  For T(P,H), the error (in K) was ~0.1% near the saturation curve, but increased at higher H values to 2% or higher.  With the correction, error is < 0.0002% over the full range.   I'll push this patch out this weekend.
